name: Python_Tests

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 0 1 * * # Run once a month on the 1st at 00:00 UTC
  workflow_dispatch:

jobs:
  example_matrix:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up pip and uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Install pytest
        run: uv pip install pytest
      - name: Install local COBRAk
        run: uv pip install .
      - name: Run pytest
        run: pytest tests/ -v
